name: ci

on:
    push:
        branches:
            - 'main'
        tags:
            - 'v*'
    pull_request:
        branches:
            - 'main'
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                tags: ghcr.io/nharrow/serenity:latest
                outputs: type=docker,dest=${{ runner.temp }}/serenity-build.tar

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: serenity-build
                path: ${{ runner.temp }}/serenity-build.tar

    push:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ github.event_name != 'pull_request' }}

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                    name: serenity-build
                    path: ${{ runner.temp }}

            - name: Load image
              run: docker load --input ${{ runner.temp }}/serenity-build.tar

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Push
              run: docker push ghcr.io/nharrow/serenity:latest
